api/urls.py
from knox import views as knox_views
from api.views import LoginAPI, RegisterAPI, UserAPI, ChangePasswordView, UserAccountSetup, UserVerification, \
    UserTermsAndCondition, ShipmentDetails, ResendVerificationEmail, ShipmentFileImport, download_file, \
    UserReturnAddress, Payment, BatchDetails, PrepPackShipDetails, PickupDetails, ForgotPasswordView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "api"

urlpatterns = [
    path('api/register/', RegisterAPI.as_view(), name='register'),
    path('api/login/', LoginAPI.as_view(), name='login'),
    path('api/logout/', knox_views.LogoutView.as_view(), name='logout'),
    path('api/logoutall/', knox_views.LogoutAllView.as_view(), name='logoutall'),
    path('api/user/', UserAPI.as_view(), name='user'),
    path('api/change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('api/forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('api/user-account-setup/', UserAccountSetup.as_view(), name='user-account-setup'),
    path('api/verify-user/', UserVerification.as_view(), name='verify-user'),
    path('api/terms-and-condition/', UserTermsAndCondition.as_view(), name='terms-and-condition'),
    path('api/resend-verification/', ResendVerificationEmail.as_view(), name='resend-verification'),
    path('api/shipment/', ShipmentDetails.as_view(), name='shipment'),
    path('api/import-shipment/', ShipmentFileImport.as_view(), name='shipment-import'),
    path('api/shipment/<str:file_name>', download_file),
    path('api/create-payment-intent/', Payment.as_view(), name='create-payment'),
    path('api/return-address/', UserReturnAddress.as_view(), name='user-return-address'),
    path('api/batch/', BatchDetails.as_view(), name='batch-details'),
    path('api/prep-pack-ship/', PrepPackShipDetails.as_view(), name='prep-pack-ship-details'),
    path('api/pickup-details/', PickupDetails.as_view(), name='pickup-details'),
    path('', views.homepage, name='home-page'),
    path('blog/', views.blogpage, name='blog-page'),
    path('ca-to-us/', views.ca_to_us, name='ca-to-us-page'),
    path('us-to-ca/', views.us_to_ca, name='us-to-ca-page'),
    path('contact/', views.contactpage, name='contact-page'),
    path('pack/', views.packagepage, name='package-page'),
    path('why-box/', views.whybuypage, name='why-box'),
    path('pricing/', views.pricepage, name='price'),
    path('blog/<slug:slug>/', views.blogdetails, name='blog-detail'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

buyboxProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('api.urls')),
    path('api/password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Buybox Administration"

api/views.py
from cmath import e
from datetime import datetime
from functools import partial
import json
import stripe
from django.contrib.auth import login
from django.http import HttpResponse, JsonResponse
from django.template.loader import get_template
from django.views.decorators.csrf import csrf_exempt
from rest_framework.authtoken.serializers import AuthTokenSerializer
from knox.views import LoginView as KnoxLoginView
from rest_framework.views import APIView
from rest_framework import generics, permissions
from rest_framework.response import Response
from knox.models import AuthToken
from .serializers import UserSerializer, RegisterSerializer, ChangePasswordSerializer, UserAccountDetailsSerializer, \
    ShipmentSerializer, ImportShipmentSerializer, AddressSerializer, BatchSerializer, BatchSerializerPost, PrepPackShipSerializer, \
    BranchSerializer, \
    RegionSerializer, PickupSerializer
from rest_framework import status
from django.contrib.auth.models import User
from rest_framework.permissions import IsAuthenticated 
from .models import UserAccountDetails, Region, Branch, Postage, Shipment, ShippingUser, ShipmentImport, \
    Address, Batch, PrepPackShip, Pickup, WhyBuyBox, Blog, BlogDetail
from knox.auth import TokenAuthentication
from django.conf import settings
from django.core.mail import EmailMessage
import ast
from django.shortcuts import render
from django.contrib.auth.hashers import make_password



# views.py

from django.core.mail import EmailMessage


def send_forgot_password_email(user):
    token = AuthToken.objects.filter(user=user).latest('created')
    forgot_password_link = settings.FRONTEND_URL + f'/update-password/?{str(token)}'
    subject = "Forgot Password"
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [user.email, ]
    context = {'username': user.username, 'forgot_password_link': forgot_password_link}

    message = get_template("forgot_password_email.html").render(context)
    mail = EmailMessage(
        subject=subject,
        body=message,
        from_email=email_from,
        to=recipient_list,
    )
    mail.content_subtype = "html"
    mail.send()

    return forgot_password_link


# Function to send email to user for verification
def send_email_verification(user):
    token = AuthToken.objects.filter(user=user).latest('created')
    # token = token
    verify_link = settings.FRONTEND_URL + '/verify/' + str(token) + '?user_id=' + str(user.id)
    subject = "Email Verification"
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [user.email, ]
    message = get_template("verify_email.html").render({
        'username': user.username,
        'verify_url': verify_link,
    })
    mail = EmailMessage(
        subject=subject,
        body=message,
        from_email=email_from,
        to=recipient_list,
    )
    mail.content_subtype = "html"
    mail.send()

    return verify_link

def homepage(request):
    return render(request, 'index.html')

def pricepage(request):
    return render(request, 'price.html')

def blogdetails(request, slug):
    blog = BlogDetail.objects.get(slug=slug)
    return render(request, 'blog-detail.html', {'blog': blog})

def blogpage(request):
    if request.method == 'POST':
        blog = Blog.objects.create(
            email = request.POST.get('email'),
        )
        blog.save()
        return render(request, 'blog.html')
    blogs = BlogDetail.objects.all()
    return render(request, 'blog.html', {'blogs': blogs})

def ca_to_us(request):
    return render(request, 'ca-to-usa.html')

def contactpage(request):
    return render(request, 'contact.html')

def packagepage(request):
    return render(request, 'pack.html')

def us_to_ca(request):
    return render(request, 'usa-to-ca.html')

def whybuypage(request):
    if request.method == 'POST':
        why_buy = WhyBuyBox.objects.create(
            name = request.POST.get('name'),
            email = request.POST.get('email'),
            message = request.POST.get('message')
        )
        why_buy.save()
        return render(request, 'why-box.html')

    return render(request, 'why-box.html')

# Register API
class RegisterAPI(generics.GenericAPIView):
    serializer_class = RegisterSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        if not User.objects.filter(email=request.data['email']).exists():
            user = serializer.save()
            token = AuthToken.objects.create(user)[1]
            verify_link = send_email_verification(user)
            user.is_active = False
            user.save()
            return Response({
            "user": UserSerializer(user, context=self.get_serializer_context()).data,
            "token": token,
            "is_agree": False,
            "is_verified": False,
            "is_account_setup_completed": False,
            "verification_link": verify_link
            })
        else:
            return Response({"Error": "Email Already Exists"})


# Login API
class LoginAPI(KnoxLoginView):
    permission_classes = (permissions.AllowAny,)

    def post(self, request, format=None):
        serializer = AuthTokenSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        login(request, user)
        response = super(LoginAPI, self).post(request, format=None)
        user_account_details = UserAccountDetails.objects.filter(user=request.user)
        response.data['user'] = UserSerializer(user).data
        if user_account_details.exists():
            user_account_details = user_account_details.first()
            response.data['is_account_setup_completed'] = True
            response.data['is_agree'] = user_account_details.is_agree
            response.data['is_verified'] = user.is_active
            response.data['user']['account'] = UserAccountDetailsSerializer(user_account_details).data
        else:
            # Fetch Regions and branches
            region_branches = []
            branches = Branch.objects.all()
            for branch in branches:
                region_serializer = BranchSerializer(branch)
                region_branches.append(region_serializer.data)
            regions = Region.objects.values_list('pk', 'name')

            response.data['user']['region_list'] = regions
            response.data['user']['region_branches'] = region_branches
            response.data['is_account_setup_completed'] = False
            response.data['is_agree'] = False
            response.data['is_verified'] = True
        return response


# Get User API
class UserAPI(generics.RetrieveAPIView):
    permission_classes = [permissions.IsAuthenticated,]
    serializer_class = UserSerializer

    def get_object(self):
        return self.request.user


class ChangePasswordView(generics.UpdateAPIView):
    """
    An endpoint for changing password.
    """
    serializer_class = ChangePasswordSerializer
    model = User
    permission_classes = (IsAuthenticated,)

    def get_object(self, queryset=None):
        obj = self.request.user
        return obj

    def update(self, request, *args, **kwargs):
        self.object = self.get_object()
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            # Check old password
            if not self.object.check_password(serializer.data.get("old_password")):
                return Response({"old_password": ["Wrong password."]}, status=status.HTTP_400_BAD_REQUEST)
            # set_password also hashes the password that the user will get
            self.object.set_password(serializer.data.get("new_password"))
            self.object.save()
            response = {
                'status': 'success',
                'code': status.HTTP_200_OK,
                'message': 'Password updated successfully',
                'data': []
            }

            return Response(response)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ForgotPasswordView(generics.UpdateAPIView):

    permission_classes = (permissions.AllowAny,)

    def get(self, request, *args, **kwargs):
        email = self.request.query_params.get('email')

        try:
            user = User.objects.get(email=email)
            forgot_password_link = send_forgot_password_email(user)
            return Response(
                {"message": "Verification link has been sent. Please Check your email",
                 "forgot_password_link": forgot_password_link},
                status=status.HTTP_200_OK
            )
        except User.DoesNotExist:
            return Response(
                {"message": "Account not found. Please provide a valid email"},
                status=status.HTTP_404_NOT_FOUND
            )

    def put(self, request, *args, **kwargs):
        password = request.data.get("password")
        user_name = request.data.get("user_name")

        try:
            user = User.objects.get(username=user_name)
            user.password = make_password(password)
            user.save()

            return Response(
                {"message": "Password updated successfully"},
                status=status.HTTP_200_OK
            )
        except User.DoesNotExist:
            return Response(
                {"message": "Account not found. Please provide a valid email"},
                status=status.HTTP_404_NOT_FOUND
            )

class UserAPI(APIView):
    permission_classes = [IsAuthenticated,]

    def get(self, request, *args, **kwargs):
        account = UserAccountDetails.objects.filter(user = request.user.id)
        serializer = UserAccountDetailsSerializer(account, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


# Verify user functionality
class UserVerification(APIView):
    permission_classes = (permissions.AllowAny,)

    def get(self, request):

api/templates/blog-detail.html
{% extends "master.html" %}

{% block title %}
    {{blog.title}}
{% endblock %}

{% block content %}
 <section class="blogs">
            <div class="main_container">
                <div class="content_sec">
                    <h2 class="title_after title_before">{{blog.title}}</h2>
                    <div class="blogs_sec">
                        <div class="blog">
                            <div class="blog_content">
                                <h3>How to Ship from Canada to USA</h3>
                                <div class="meta">
                                            <span>{{blog.created_date}}</span>
                                            <span>{{blog.author}}</span>
                                        </div>
                                        <h6>{{blog.category}}</h6>
                                        <p>
                                            {{blog.description}}
                                        </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
 </section>

{% endblock %}

api/templates/blog.html
{% extends "master.html" %}

{% block title %}
    Why Buybox Express
{% endblock %}



{% block content %}
        
        <!-- Inner Hero Banner -->
        <section class="hero_banner why_box">
            <div class="main_container">
                <div class="content_sec">
                    <div class="leftpan">
                        <h5 class="hero_sub_title">WELCOME TO THE BUYBOX EXPRESS BLOG!</h5>
                        <h1 class="main_title">Grow your eCommerce Business in Canada</h1>   
                        <p class="para_title para_big_title">
                            “I need more inbox clutter,” said no one ever. That’s why we’ll only send practical emails that will
                            improve your business, once a week. You’ll receive the best tips, strategies, and news on Canadian eCommerce.
                        </p>
                        <form method="post" action="/blog/">
                            {% csrf_token %}
                        <div class="subscribe_box">
                             <input type="email" name="email" placeholder="Enter your email">
                            <button>Subscribe</button>
                        </div>
                        </form>
                    </div>
                    <div class="rightpan">
                        <a href="#">
                            <img src="../static/img/why_box.png" alt="">
                        </a>                        
                    </div>
                </div>
            </div>
        </section>

        <section class="blogs">
            <div class="tab_sec">                           
                    <div class="tab_btns">    
                        <div class="main_container">
                            <button class="tab-button active" onclick="openTab(1)">Blog Home</button>
                            <button class="tab-button" onclick="openTab(2)">News & Announcements</button>
                            <button class="tab-button" onclick="openTab(3)">Ecommerce Tips</button>
                            <button class="tab-button" onclick="openTab(4)">Shipping & Fulfillment</button>
                            <button class="tab-button" onclick="openTab(5)">Marketplace Strategies</button>
                            <button class="tab-button" onclick="openTab(6)">Customer Spotlights</button>
                        </div>
                    </div>                
                    <div class="main_container">
                        <div class="tab_content">
                            <div class="tab" id="tab1" style="display: block;">
                                <h2>Latest Blog Posts</h2>
                                <div class="blogs_con">
                                {% for blog in blogs %}
                                    {% if blog.tab == 'tab1' %}
                                    <div class="blog_col">
                                        <h3> {{blog.title}}</h3>
                                        <div class="meta">
                                            <span>{{blog.created_date}}</span>
                                            <span>{{blog.author}}</span>
                                        </div>
                                        <h6>{{blog.category}}</h6>
                                        <p>                                            
                                            {{blog.description}}
                                        </p>
                                        <a href="{% url 'api:blog-detail' slug=blog.slug %}">Read More</a>
                                    </div>
                                        {% endif %}
                                {% endfor %}
                                </div>
                            </div>

                            <div class="tab" id="tab2">

                                <h2>Latest News & Announcements</h2>
                                <div class="blogs_con">
                                {% for blog in blogs %}
                                    {% if blog.tab == 'tab2' %}
                                    <div class="blog_col">
                                        <h3> {{blog.title}}</h3>
                                        <div class="meta">
                                            <span>{{blog.created_date}}</span>
                                            <span>{{blog.author}}</span>
                                        </div>
                                        <h6>{{blog.category}}</h6>
                                        <p>                                            
                                            {{blog.description}}
                                        </p>
                                        <a href="{% url 'api:blog-detail' slug=blog.slug %}">Read More</a>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                                </div>
                            </div>

                            <div class="tab" id="tab3">
                                <h2>Latest Ecommerce Tips</h2>
                                <div class="blogs_con">
                                {% for blog in blogs %}
                                    {% if blog.tab == 'tab3' %}
                                    <div class="blog_col">
                                        <h3>{{blog.title}}</h3>
                                        <div class="meta">
                                            <span>{{blog.create_date}}</span>
                                            <span>{{blog.author}}</span>
                                        </div>
                                        <h6>{{blog.category}}</h6>
                                        <p>
                                            {{blog.description}}
                                        </p>
                                        <a href="{% url 'api:blog-detail' slug=blog.slug %}">Read More</a>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                                </div>
                            </div>

                            <div class="tab" id="tab4">
                                <h2>Latest Shipping & Fulfillment</h2>
                                <div class="blogs_con">
                                {% for blog in blogs %}
                                    {% if blog.tab == 'tab4' %}
                                    <div class="blog_col">
                                        <h3>{{blog.title}}</h3>
                                        <div class="meta">
                                            <span>{{blog.create_date}}</span>
                                            <span>{{blog.author}}</span>
                                        </div>
                                        <h6>{{blog.category}}</h6>
                                        <p>                                            
                                            {{blog.description}}
                                        </p>
                                        <a href="{% url 'api:blog-detail' slug=blog.slug %}">Read More</a>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                                </div>
                            </div>

                            <div class="tab" id="tab5">
                                <h2>Latest Marketplace Strategies</h2>
                                <div class="blogs_con">
                                {% for blog in blogs %}
                                    {% if blog.tab == 'tab5' %}
                                    <div class="blog_col">
                                        <h3>{{blog.title}}</h3>
                                        <div class="meta">
                                            <span>{{blog.create_date}}</span>
                                            <span>{{blog.author}}</span>
                                        </div>
                                        <h6>{{blog.category}}</h6>
                                        <p>
                                            {{blog.description}}
                                        </p>
                                        <a href="{% url 'api:blog-detail' slug=blog.slug %}">Read More</a>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                                </div>
                            </div>

                            <div class="tab" id="tab6">
                                <h2>Latest Customer Spotlights</h2>
                                <div class="blogs_con">
                                {% for blog in blogs %}
                                    {% if blog.tab == 'tab6' %}
                                    <div class="blog_col">
                                        <h3>{{blog.title}}</h3>
                                        <div class="meta">
                                            <span>{{blog.create_date}}</span>
                                            <span>{{blog.author}}</span>
                                        </div>
                                        <h6>{{blog.category}}</h6>
                                        <p>
                                            {{blog.description}}
                                        </p>
                                        <a href="{% url 'api:blog-detail' slug=blog.slug %}">Read More</a>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </section>

<script src="../static/js/custom2.js"></script>
{% endblock %}

api/templates/contact.html
{% extends "master.html" %}

{% block title %}
    Contact Us
{% endblock %}

{% block content %}
        <section class="contact_us">
            <div class="main_container">
                <h1>Contact Us</h1>
                <p>Get the support you need, send us a message, or learn more about us</p>
                <div class="content_sec">
                    <div class="contact_col">
                        <img src="../static/img/contact_1.png" alt="">
                        <h3>Message</h3>
                        <p>Want to report an issue, request a feature, share your story, submit feedback, or learn more?</p>
                        <a href="#">Send us a message <img src="../static/img/long_arrow.png" alt=""></a>
                    </div>
                    <div class="contact_col">
                        <img src="../static/img/contact_2.png" alt="">
                        <h3>Client Support Hours</h3>
                        <p>
                            Mon to Fri - 10am to 9pm ET 
                        </p>
                        <p>
                            Sat – Closed
                        </p>
                        <p>
                            Sun – 10am to 5pm ET
                        </p>
                    </div>
                    <div class="contact_col">
                        <img src="../static/img/contact_3.png" alt="">
                        <h3>Toll-Free Phone</h3>
                        <p>Call us and our support team will be happy to help.</p>
                        <a href="#"><img src="../static/img/sub_call.png" alt=""> +(905) 780-3083</a>
                    </div>
                    <div class="contact_col">
                        <img src="../static/img/contact_4.png" alt="">
                        <h3>Find A Location</h3>
                        <p>Learn more about drop off locations near you</p>
                        <a href="#"> View Locations & Hours <img src="../static/img/long_arrow.png" alt=""></a>
                    </div>
                    <div class="contact_col">
                        <img src="../static/img/contact_5.png" alt="">
                        <h3>Social Media</h3>
                        <div class="social_media">
                            <a href="https://www.linkedin.com/company/buybox-express/mycompany/?viewAsMember=true"><i class="fa fa-linkedin-square"></i></a>
                            <a href="https://www.facebook.com/Buyboxexpress"><i class="fa fa-facebook-square"></i></a>
                            <a href="https://twitter.com/BuyboxExpress"><i class="fa fa-twitter-square"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}